# Generated by Django 4.2.4 on 2023-08-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('carType', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('fuel', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=200)),
                ('hourRate', models.IntegerField()),
                ('dayRate', models.IntegerField()),
                ('monthRate', models.IntegerField()),
            ],
        ),
    ]
