# Generated by Django 4.2.4 on 2023-08-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickUpLoc', models.CharField(max_length=100)),
                ('dropOffLoc', models.CharField(max_length=100)),
                ('pickUpDate', models.DateField()),
                ('dropOffDate', models.DateField()),
                ('pickUpTime', models.TimeField()),
                ('carId', models.IntegerField()),
                ('userId', models.IntegerField(null=True)),
                ('adminId', models.IntegerField(null=True)),
            ],
        ),
    ]
