# Generated by Django 4.2.4 on 2023-08-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='cars.car'),
        ),
    ]
