# Generated by Django 4.2.4 on 2023-08-19 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0002_alter_order_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.car'),
        ),
    ]
