# Generated by Django 4.2.4 on 2023-08-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('orders', '0003_alter_order_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='authentication.user'),
        ),
    ]
